-- Client questions
-- 1. How many completed applications were submitted for the 2018-2019 and the 2019-2020 academic years? 
SELECT CA.ACADEMIC_YEAR, COUNT(idRENTAL_APPLICATION) NUMBER_OF_APPLICANTS
FROM RENTAL_APPLICATION RA, CALENDER_YEAR CA
WHERE RA.idCALENDER_YEAR = CA.idCALENDER_YEAR
GROUP BY RA.idCALENDER_YEAR;

-- 2.  Of the students living in Cedar Hall North and South, what was the most popular meal plan selection?
CREATE TABLE TEMP (SELECT NUMBER_OF_MEALS, COUNT(*) NUMBER
					 FROM MEAL_PLAN MP, ROOM R, RENTAL_AGREEMENT RA
					 WHERE MP.idMEAL_PLAN = RA.idMEAL_PLAN AND RA.idROOM = R.idROOM AND R.idBUILDING = '1');
SELECT NUMBER_OF_MEALS
FROM TEMP
WHERE NUMBER = (SELECT MAX(NUMBER)
				FROM TEMP);
DROP TABLE TEMP;

-- 3. How many maintenance requests were submitted for Ponderosa Terrace during the 2018-2019 academic year and what repair was most requested?
CREATE TABLE TEMP(SELECT M.MAINTENANCE_TYPE, COUNT(ME.idMAINTENANCE) AMOUNT 
				  FROM MAINTENANCE M, MAINTENANCE_EVENT ME
                  WHERE M.idMAINTENANCE = ME.idMAINTENANCE
                  GROUP BY M.MAINTENANCE_TYPE);
SELECT MAINTENANCE_TYPE, AMOUNT
FROM TEMP
WHERE AMOUNT = (SELECT MAX(AMOUNT)
				FROM TEMP);
DROP TABLE TEMP;

-- 4. According to the roommate matching survey, how many students listed on their application that they were both a "gamer, or occasional gamer" and a "night owl"?
SELECT COUNT(idSTUDENT) LATE_NIGHT_GAMERS
FROM STUDENT_SURVEY_ANSWERS SA
WHERE (SA.GAMER = 'occasionally' OR SA.GAMER = 'gamer') AND SA.SLEEP_SCHEDULE = 'Night owl';

-- 5. Of the female students not living in Cedar Hall, how many selected a meal plan?
SELECT COUNT(RA.idMEAL_PLAN) GIRLS_WITHOUT_MEAL_PLAN
FROM RENTAL_AGREEMENT RA, MEAL_PLAN MP, STUDENT S
WHERE RA.idSTUDENT = S.idSTUDENT AND RA.idMEAL_PLAN = MP.idMEAL_PLAN AND 
	RA.idBUIDLING != '1' AND S.GENDER = 'F' AND RA.idMEAL_PLAN != '3004';

-- Instructor questions
-- 1. What is the total cost of maintenance for each building during for each year?
SELECT B.BUILDING_NAME, YEAR(ME.START_DATE) YEAR, SUM(COST) MAINTENANCE_COST
FROM MAINTENANCE_EVENT ME, BUILDING B
WHERE ME.idBUILDING = B.idBUILDING AND ME.idBUILDING = '1'
GROUP BY YEAR(ME.START_DATE)
UNION
SELECT B.BUILDING_NAME, YEAR(ME.START_DATE) YEAR, SUM(COST) MAINTENANCE_COST
FROM MAINTENANCE_EVENT ME, BUILDING B
WHERE ME.idBUILDING = B.idBUILDING AND ME.idBUILDING = '2'
GROUP BY YEAR(ME.START_DATE)
UNION
SELECT B.BUILDING_NAME, YEAR(ME.START_DATE) YEAR, SUM(COST) MAINTENANCE_COST
FROM MAINTENANCE_EVENT ME, BUILDING B
WHERE ME.idBUILDING = B.idBUILDING AND ME.idBUILDING = '3'
GROUP BY YEAR(ME.START_DATE)
UNION
SELECT B.BUILDING_NAME, YEAR(ME.START_DATE) YEAR, SUM(COST) MAINTENANCE_COST
FROM MAINTENANCE_EVENT ME, BUILDING B
WHERE ME.idBUILDING = B.idBUILDING AND ME.idBUILDING = '4'
GROUP BY YEAR(ME.START_DATE);

-- 2. How many students didn't get a rental contract and applied for a specific year?
SELECT COUNT(*) 
FROM RENTAL_AGREEMENT 
WHERE idSTUDENT NOT IN (SELECT idSTUDENT FROM RENTAL_APPLICATION);

-- 3.  How many students are not put in the building they requested for the 2018 academic year?
SELECT (100 - COUNT(SA.BUILDING_CHOICE))
FROM STUDENT_SURVEY_ANSWERS SA, RENTAL_AGREEMENT RA, BUILDING B
WHERE SA.idSTUDENT = RA.idSTUDENT AND RA.idBUIDLING = B.idBUILDING
	AND SA.BUILDING_CHOICE = B.BUILDING_NAME;

-- 4.  Show the meal plans and the number of students selecting each one for 2018?
SELECT NUMBER_OF_MEALS, COUNT(idSTUDENT) NUMBER_OF_STUDENTS
FROM MEAL_PLAN MP, RENTAL_AGREEMENT RA
WHERE RA.idMEAL_PLAN = MP.idMEAL_PLAN AND MP.idMEAL_PLAN = '3004'
UNION
SELECT NUMBER_OF_MEALS, COUNT(idSTUDENT) NUMBER_OF_STUDENTS
FROM MEAL_PLAN MP, RENTAL_AGREEMENT RA
WHERE RA.idMEAL_PLAN = MP.idMEAL_PLAN AND MP.idMEAL_PLAN = '3000'
UNION
SELECT NUMBER_OF_MEALS, COUNT(idSTUDENT) NUMBER_OF_STUDENTS
FROM MEAL_PLAN MP, RENTAL_AGREEMENT RA
WHERE RA.idMEAL_PLAN = MP.idMEAL_PLAN AND MP.idMEAL_PLAN = '3001'
UNION
SELECT NUMBER_OF_MEALS, COUNT(idSTUDENT) NUMBER_OF_STUDENTS
FROM MEAL_PLAN MP, RENTAL_AGREEMENT RA
WHERE RA.idMEAL_PLAN = MP.idMEAL_PLAN AND MP.idMEAL_PLAN = '3002'
UNION
SELECT NUMBER_OF_MEALS, COUNT(idSTUDENT) NUMBER_OF_STUDENTS
FROM MEAL_PLAN MP, RENTAL_AGREEMENT RA
WHERE RA.idMEAL_PLAN = MP.idMEAL_PLAN AND MP.idMEAL_PLAN = '3003';

-- 5.  Check if the gender of the students put together in apartments are the same for 2018
SELECT R.idROOM, R.idBUILDING, GENDER
FROM ROOM R, STUDENT S, RENTAL_AGREEMENT RA
WHERE RA.idSTUDENT = S.idSTUDENT AND R.ROOM_GENDER != S.GENDER
GROUP BY R.idROOM;

-- Personal questions
-- 1. What are the total hours of maintenance for each building for each year?
SELECT B.BUILDING_NAME, YEAR(ME.START_DATE) YEAR, SUM(TOTAL_HOURS) TOTAL_HOURS
FROM MAINTENANCE_EVENT ME, BUILDING B
WHERE ME.idBUILDING = B.idBUILDING AND ME.idBUILDING = '1'
GROUP BY YEAR(ME.START_DATE)
UNION
SELECT B.BUILDING_NAME, YEAR(ME.START_DATE) YEAR, SUM(TOTAL_HOURS) TOTAL_HOURS
FROM MAINTENANCE_EVENT ME, BUILDING B
WHERE ME.idBUILDING = B.idBUILDING AND ME.idBUILDING = '2'
GROUP BY YEAR(ME.START_DATE)
UNION
SELECT B.BUILDING_NAME, YEAR(ME.START_DATE) YEAR, SUM(TOTAL_HOURS) TOTAL_HOURS
FROM MAINTENANCE_EVENT ME, BUILDING B
WHERE ME.idBUILDING = B.idBUILDING AND ME.idBUILDING = '3'
GROUP BY YEAR(ME.START_DATE)
UNION
SELECT B.BUILDING_NAME, YEAR(ME.START_DATE) YEAR, SUM(TOTAL_HOURS) TOTAL_HOURS
FROM MAINTENANCE_EVENT ME, BUILDING B
WHERE ME.idBUILDING = B.idBUILDING AND ME.idBUILDING = '4'
GROUP BY YEAR(ME.START_DATE);

-- 2. According to the roommate matching survey, how many students listed on their application that they were both clean and liked quiet?
SELECT COUNT(idSTUDENT) NUMBER_OF_CLEAN_AND_QUIET_STUDENTS
FROM STUDENT_SURVEY_ANSWERS SA
WHERE SA.CLEANLINESS = 'Very neat & tidy' AND SA.PERFERED_NOISE_LEVEL = 'Quiet';


-- 3. How many students are non-smokers, newbies, and have a personality of very reserved?
SELECT COUNT(idSTUDENT) NUMBER_OF_NEWBIE_NON_SMOKERS
FROM STUDENT_SURVEY_ANSWERS SA
WHERE (SA.SMOKER = 'Y' AND SA.NEWBIE = 'Y') AND SA.PERSONALITY = 'Very Reserved';

-- 4. How many female students have meal plans? How many male?
SELECT GENDER, COUNT(*) STUDENTS_WITH_MEAL_PLAN
FROM RENTAL_AGREEMENT RA, MEAL_PLAN MP, STUDENT S, ROOM R, BUILDING B
WHERE RA.idSTUDENT = S.idSTUDENT AND RA.idROOM = R.idROOM AND R.idBUILDING = B.idBUILDING AND RA.idMEAL_PLAN = MP.idMEAL_PLAN AND MP.idMEAL_PLAN != '3004'
GROUP BY GENDER;

-- 5. How many students plan on playing sports and consider themselves liberals politically?
SELECT COUNT(idSTUDENT) LIBERAL_JOCKS
FROM STUDENT_SURVEY_ANSWERS SA
WHERE SA.SPORTS = 'Y' AND SA.POLITICS = ' Liberal';



















